### ISSUE TITLE
Alternate object class syntax does not work for some objects.

### ISSUE THREAD

**Issue by bdcoelho** [hongyuanjia/eplusr#169] opened 2019-12-09 01:38 UTC
I noticed an issue with calling the IDF object class AirTerminal:SingleDuct:Mixer in eplusr.
I'm able to call it in the format **model$AirTerminal_SingleDuct_Mixer** but not as **model$"AirTerminal:SingleDuct:Mixer"**. That syntax has generally worked. I'm not sure if any other classes are affected. 

See below.

> NewModel$"AirTerminal:SingleDuct:Mixer"
NULL

> NewModel$AirTerminal_SingleDuct_Mixer
$`RYDALMERE_G_B_Office_2 DOAS Air Terminal`
<IdfObject: `AirTerminal:SingleDuct:Mixer`> [ID:3714] `RYDALMERE_G_B_Office_2 DOAS Air Terminal`
-- COMMENTS ---------------------------------------------------------------------------------------------------------------------------
!Create mixer
! Set Mixer Secondary Air Inlet Node Name to node from equipment connections Zone Air Exhaust Node or NodeList Name
! Set Mixer Primary Air Inlet Node Name to node from Terminal unit Air Inlet Node Name
-- VALUES -----------------------------------------------------------------------------------------------------------------------------
Class: <AirTerminal:SingleDuct:Mixer>
+- 1: "RYDALMERE_G_B_Office_2 DOAS Air Terminal",  !- Name
|- 2: "ZoneHVAC:FourPipeFanCoil",  !- ZoneHVAC Unit Object Type
|- 3: "RYDALMERE_G_B_Office_2 Fan Coil",  !- ZoneHVAC Unit Object Name
|- 4: "Fan Coil Inlet",   !- Mixer Outlet Node Name
|- 5: "RYDALMERE_G_B_Office_2 Zone Equip Inlet",  !- Mixer Primary Air Inlet Node Name
|- 6: "RYDALMERE_G_B_Office_2 Exhaust Node",  !- Mixer Secondary Air Inlet Node Name
|- 7: "InletSide",        !- Mixer Connection Type
|- 8: "RYDALMERE_G_B_Office_2 DSOA",  !- Design Specification Outdoor Air Object Name
\- 9: "CurrentOccupancy"; !- Per Person Ventilation Rate Mode

Regards,
Ben

**Comment by bdcoelho** [comment] 2019-12-09 01:53
Update:
It works for some models but not others.

**Comment by hongyuanjia** [comment] 2019-12-09 02:57
@bdcoelho That's for reporting this. However, I cannot reproduce this behavior on my side. Can you share one model that failed to let me test? Thanks

**Comment by bdcoelho** [comment] 2019-12-09 03:58
I'm able to reproduce the behavior in some situations. I've attached 2 idf's and the code that reproduces the problem as text.

[TestModel.idf.txt](https://github.com/hongyuanjia/eplusr/files/3937816/TestModel.idf.txt)
[TestTemplate.idf.txt](https://github.com/hongyuanjia/eplusr/files/3937817/TestTemplate.idf.txt)
[testcode.r.txt](https://github.com/hongyuanjia/eplusr/files/3937818/testcode.r.txt)


I'm reading in both idf's and inserting the AirTerminal:SingleDuct:Mixer object into the TestModel IDF.
The problem shows up after this when I try to retrieve the object. I've validate_level to "none" since I don't want to validate the IDF immediately as I'm building it.

**Comment by hongyuanjia** [comment] 2019-12-09 05:10
Thanks @bdcoelho! This is a bug as reported in #105 and has been fixed in 8ca13e2.

You can install the development version to try it out: `remotes::install_github("hongyuanjia/eplusr")`

The development version fixes lots of [bugs](https://github.com/hongyuanjia/eplusr/issues?q=is%3Aissue+milestone%3A0.11.0+is%3Aclosed+label%3Abug) since v0.10.3. I will update a new release to CRAN once all documentation refactor work finishes (#156).

Maybe I should move quicker now.

For now I will close this issue. Feel free to reopen it if you still encounter the same problem with the development version.

**Closed by hongyuanjia** 2019-12-09 05:10 UTC
Labels: duplicate
