### ISSUE TITLE
replace value

### ISSUE THREAD

**Issue by yatingchen** [hongyuanjia/eplusr#55] opened 2019-07-06 21:12 UTC
Dear Hongyuan,

I saw a function in the documents called $replace_value(), but I cannot find it in current packages. Will you add it in the future?

![image](https://user-images.githubusercontent.com/38569061/60761174-ded20880-a008-11e9-950d-8906859998d1.png)

**Comment by hongyuanjia** [comment] 2019-07-07 03:45
This new function has already implemented in the current CRAN version (v0.10.2). Can you show what error message you get when you tried to call `$replace_value()`?

**Comment by yatingchen** [comment] 2019-07-08 01:01
I used:
`remotes::install_github("hongyuanjia/eplusr")`
to update the package and got the error:

> Error: attempt to apply non-function

**Comment by hongyuanjia** [comment] 2019-07-08 01:42
Sorry, I failed to reproduce this problem. I just tested and this method works fine on my side.

**Comment by hongyuanjia** [comment] 2019-07-08 08:48
@yatingchen eplusr v0.10.3 has just landed on CRAN. You can try it out to see if this error goes away.

**Comment by yatingchen** [comment] 2019-07-08 14:15
Sorry, error remained the same as before

![image](https://user-images.githubusercontent.com/38569061/60817113-a80f0600-a160-11e9-9944-1a34ad414b59.png)

**Comment by hongyuanjia** [comment] 2019-07-08 14:22
Please make sure `changed` is an `Idf` object.

![image](https://user-images.githubusercontent.com/20545387/60817690-bd227e00-a1ce-11e9-9117-d8182c49cca3.png)

**Comment by yatingchen** [comment] 2019-07-08 15:07
Thanks for your information. 
But can you give me an example to show how to use it? Will it change an object or a value in the object?

Thanks

**Comment by hongyuanjia** [comment] 2019-07-08 15:34
`$replace_value()` works just like `gsub()`. It works on object values, including object names. It lets you directly treat all field values as character and modifies them in-place using regular expressions.

The [documentation](https://hongyuanjia.github.io/eplusr/reference/Idf.html#object-modification) on `$replace_value()` in `Idf` class contains a simple use case:

```r
idf <- read_idf(file.path(eplus_config(9.0)$dir, "ExampleFiles/HospitalBaseline.idf"))

# replace "METAL" with "Metal" in all fields
idf$replace_value("METAL", "Metal", fixed = TRUE)
```

Note that it is recommended to use `$search_value()` with the same regex first to see what fields `$replace_value()` will work on. `$replace_value()` should be treated as a low-level method, because it takes all field values as a whole and does not respect any class specification (i.e. you cannot use `$replace_value()` only on certain objects in a class.

For most of the time, newly added method `$update()` (in v0.10.3) together with other methods should be enough for most of your needs. Any feature requests are extremely welcome.

As this is not a bug, I will close it  now.

**Closed by hongyuanjia** 2019-07-08 15:34 UTC
Labels: question
