### ISSUE TITLE
input start year of weather data

### ISSUE THREAD

**Issue by chenwei2017** [hongyuanjia/eplusr#101] opened 2019-08-28 20:26 UTC
![weather data](https://user-images.githubusercontent.com/26535338/63890125-ef1eb800-c9a7-11e9-946c-1b3102a88192.PNG)

Is there a problem about my weather data?
My weather data is TMY3 originated from https://energyplus.net/weather-location/north_and_central_america_wmo_region_4/USA/MA/USA_MA_Boston-Logan.Intl.AP.725090_TMY3

**Comment by hongyuanjia** [comment] 2019-08-29 00:52
Actually this is not caused by the weather file, but by the `year` argument in `$report_data()`. This bug has been fixed in a38433b208cc38cae8dc6dd9a14f9e8207963562.

Please try the development version via `remotes::install_github("hongyuanjia/eplusr")`. Let me know if you still have problem.

**Comment by hongyuanjia** [comment] 2019-08-30 03:53
Close now. Feel free to reopen it if you still have problem.

**Closed by hongyuanjia** 2019-08-30 03:53 UTC
